### ISSUE TITLE
Okruh 6 - Problematika řazení

### ISSUE THREAD

**Issue by nicki-krizek** [tomaskrizek/tul-szz-it-nv#10]
[6. - Problematika řazení](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/06_problematika_razeni/06_problematika_razeni.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @tomaskrizek |  | :eyes: |
### TODO
- [x] Zvážit, zda přidat obrázky (ne gif - pro tisk). Pouze jsem tam dal link do wiki, ale to je při vytištění k ničemu.
- [x] ~~Možná uvést pseudokód některých algoritmů?~~
- [x] Upravit zpetny chod merge sort.

**Comment by nicki-krizek** [comment]
Prozatím jsem s tím skončil. Kdyby to někdo přebral a dodělal (tipy v TODO), bylo by to fajn.

**Comment by johnymachine** [comment]
Do hlavičky zde bych přidal odkaz, ať je možné si to rovnou otevřít odsud...

Obrázky bych přidal, gif ne. Stačí napsat výrazně nakonec, že jsou na tom odkaz ty animace sortu.
Spíš než pseudo kód jsem spíš pro Javu, ta je myslím čitelná pro každého. (algoritmy.net)

**Comment by nicki-krizek** [comment]
Jestli pseudokód nebo Java, to už je celkem jedno. Klidně to může být osekaná Java (přeskočení inicializaci, definice typů apod.). Suntakticky správnej spustitelnej kód je podle mě overkill.

Spíš jde o to, jestli to vůbec uvádět. Určitě bych to nedával ke všem šešti algoritmům. Odkazy do hlaviček přidám.

**Comment by johnymachine** [comment]
Osekaná Java je rozumná volba, nemám rád takový ty moc obecný matematicky zapsaný pseudokody, mám pak problém rozeznat co je cyklus a tak =)

**Comment by nicki-krizek** [comment]
Doplnil jsem příklady algoritmů. Kód už by z toho podle me každý nějak vymyslel nebo dal dohromady, když pochopí, jak to funguje. Otázku považuju za :eyes:.

**Comment by VaclavPalik** [comment]
Pri mergesortu se budou pri zpetnym chodu sbirat presne tak, jak dochazelo k deleni, ten obrazek prosim upravit.

**Comment by nicki-krizek** [comment]
@VaclavPalik Takze jedina zmena by mela byt, ze se spoji nejdriv 4,8 a pak teprve na 2,4,8, je to tak? Kdyztak to zitra upravim.

**Comment by VaclavPalik** [comment]
Ano, zpetny chod bude neco jako vynorovani se z rekurze, kvuli tomu to bude presne takhle.
