### ISSUE TITLE
Okruh 29 - Abstraktní datové typy

### ISSUE THREAD

**Issue by johnymachine** [tomaskrizek/tul-szz-it-nv#12]
[29. - Abstraktní datové typy](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/29_abstraktni_datove_typy/29_abstraktni_datove_typy.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @johnymachine | @tomaskrizek | :eyes: |
### Verze
- [master](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/29_abstraktni_datove_typy/29_abstraktni_datove_typy.md)
- [TK-29_ADT_review](https://github.com/tomaskrizek/tul-szz-it-nv/blob/TK-29_ADT_review/29_abstraktni_datove_typy/29_abstraktni_datove_typy.md)
### TODO
- [x] ~~Odstranit sekci Operace?~~
- [ ] poladit počáteční pojmy

**Comment by nicki-krizek** [comment]
Odstavec o **ADT** podle mě obsahuje příliš moc zbytečných nebo zavádějících informací.

> programovací jazyky používají tyto ADT jako primitivní datové typy

Primitivní datový typ je něco, co je dál nedělitelné, typicky čísla, znaky atd. Všechny ADT jsou naopak složené datové typy, protože to jsou kolekce nějakých jiných objektů. 

Navrhuju změnit to na formát odrážek (spíš osobní preference) a upravit obsah.

Odstavec **Datové typy** bych vůbec neuváděl a místo toho přidal zmínku o Datových strukturách. 

**Vlastnosti**

> Přesný popis: Propojení mezi implementací a rozhraním musí být jednoznačné a úplné.

Tohle nějak nemůžu pochopit. Podle mě to tam nepatří. U ADT právě vůbec žádnou implementaci neřeším.

> Jednoduchost: Při používání se uživatel nemusí starat o vnitřní realizaci a správu ADT v paměti.

Opět nevím, jak to souvisí s ADT, neuváděl bych to. To jestli se starám o správu v paměti závisí spíš na programovacím jazyce. Stějně tak vnitřní realizaci taky neřeším, když používám třeba double.

> Uživatel nemůže zasahovat do vnitřní struktury dat.

Podle mě je zde výstižnější "Uživatel nemůže zasahovat do vnitřní struktury ADT." Pod daty si představím spíš to, co do ADT uložím. A s obsahem těch dat manipulovat samozřejmě můžu.

**Operace**
Působí to na mě opět velice zmatečně. Míchají se tam pojmy hodnoty a datový typ a podle mě to je nesprávně. Navrhuju to úplně ořezat na to podstatný.

Navíc nevím, jestli to sem vůbec patří. Spíš to je popis toho, jak často vypadá implementace v Javě (konstruktor, get, set), než že by to obecně souviselo s ADT. Mám frontu, udělám pop - a teď co to je - selektor? Modifikátor? Podle mě to udělá oboje. Určitě tyhle operace souvisí s ADT? Co třeba pokud mám strom a chci najít prvek?

Zatím jsem to tam nechal ve zkrácené formě, ale mám pocit, že tohle nesouvisí s ADT, ale spíš s Javou. Když budu mít v Pythonu

``` python
my_list = list(1, 2, 3)
a = my_list[0]
```

Je to selektor, nebo modifikátor? Je to prostě operace, která v tom listu najde a vrátí prvek.

**Seznam**

Je velký rozdíl mezi seznamem (list) a spojovým seznamem (linked list). Text popisuje spojový seznam místo seznamu. Jedna z možných implementací seznamu je linked list, ale stejně tak i dynamické pole. Kruhový seznam potom nedáva smysl - to má být kruhový spojový seznam.

V textu mi chybí operace, které lze se seznamem dělat, a asi nejpodstatnějí věc -- rozdíl mezi množinou a seznamem.

**Fronta**

Opět jsem text předělal na odrážky a upravil obsah. Neuváděl bych, že opak je zásobník.

**Zasobník**

Změna textu na odrážky. Neuváděl bych, že opakem je fronta.

**Strom**
- Změna textu na odrážky.
- Hloubka změněna na hloubku uzlu.
- Přidána výška stromu.
- Odstraněna Pravidelnost (slyším to poprvé, podle mě je to nepodstatná vlastnost v rámci strukčnosti). To stejné úplná pravidelnost.
- Změna popisu vyvazenosti.
- přidána zmínka o průchodu do hloubky / do šířky
- lepší popis XYZorder a obrázek

Ke zbytku jsem se zatím nedostal. Změny jsem pushnul do samostatné branche.

**Comment by johnymachine** [comment]
# Úvod

Souhlasím je to lepší, jen nevím jestli bych nedal, alespoň minimální souvislý text na začátek, který vypálíš rovnou když se tě zeptají.

> často se u nich uvádí časová či paměťová složitost
>  dodal bych je to důležité z hlediska efektivního návrhu algoritmu

Přidal bych

> jazyky mají ve svých standartních knihovnách obvykle obsaženy optimalizované implementace ADT

Datový typ bych nechal v úlpně zjednodušené verzi

> **Datový typ** určuje rozsah hodnot a definované operace pro proměnou daného typu.

Datové struktury, jsem zpočátku úplně nepochopil po druhém přečtený bych tam dodal:
ADT je seznam a  její DS je například linked list?

# Vlastnosti

Je to podle mě v pohodě

Přesný popis: podle mě znamená, že to má dobré a kvalitně zdokumentované api a nikde se do toho nezasahuje napřímo

Jednoduchost: nejaký pozůstatek z cečka, pro mne znamená je to dobře navržené a neřeším násilím kam se to např ve strome zarovná, proste to funguje a nemusím to ručně realokovat a tak.

**Tyto dvě se dají asi spojit**

Integrita: ekvivalent objektového zapouzdření, nemůžu si sahat přímo do použitého pole, manipuluji pouze metodami (nelze přepojovat uzly stromu ručně)

**Pravdou je, že to popisuje vlastně objektové principy ale tak nějak smíchaně a divně pojmenovaně.**

# Operace

To je prostě taková teorie, které se holt trochu překrývá. Ale myslím že to má logiku.
**Tak nějak to říká, hele nejdřív si to uskup do správné reprezentace a pak musím mít možnost to zapisovat i číst!**
- **konstruktor** zodpovídá za správnou inicializaci a sestavené platné reprezentace datového typu na základě dodaných parametrů
  (prostě kontruktor)

``` python
my_list = list(1, 2, 3)
```
- **selektor** získání konkrétní položky z vnitřní reprezentace
  (tady je get, peek, isEmpty)

``` python
a = my_list[0]
```
- **modifikátor** slouží ke změně dat
  (zde patří prostě push i pop)

``` python
my_list[0] = a
```

# Zbytek později, je to úmorné to ladit :)

**Comment by nicki-krizek** [comment]
Review doděláno. Zbytek změn viz branch, vypisovat se mi to nechce.

U datove struktury bych tam nepridaval to s tim linked listem. Spis si pod tim predstavim nejakou vlastni tridu, ktera obsahuje nejaka data a dela s nimi, co ja chci.

Vlasnosti presny popis a jednoduchost bych vynechal.

**Comment by johnymachine** [comment]
@tomaskrizek opravil jsem a mysli ze je to takto v pohode... mozna jeste
- [ ] poladit jeste zacatecni pojmy
- [x] komprimovat procházení stromem do jednoho obrazku s prihladem
- [x] porovnat operace haldy do jednotného formátu a sloučit se slozitosti
- [x] rozsirit asociativni pole + mozna obrazek priklad?

**Comment by nicki-krizek** [comment]
Popis asoc. pole je podle me dostacujici. 

Slozitost operace Decrease key a Increase key jsem uvedl log2(n), ale nejsem si jisty. Ale pokud musim ten uzel najit, tak to odpovida. Pokud bych uzel mel nalezeny a jen upravoval hodnotu, tak by to melo konstantni slozitost.

Upravu pocatecnich pojmu bych zatim odlozil na neurcito :)

Tenhle stav otazky mi prozatim prijde ok. Necham na tobe, zda to oznacit jako hotove.

**Comment by johnymachine** [comment]
Vidím to podobně, vylepšoval bych to pokud bude čas... prozatím nechám otevřené až to uvidí více očí...

**Čeká na další názory a úpravy...**

**Comment by nicki-krizek** [comment]
Do tohoto stavu se asi dostane hodne otazek, navrhuju to oznacit :eyes:, abychom to odlisili v seznamu.
