### ISSUE TITLE
Okruh 2 - Základy teorie dělitelnosti

### ISSUE THREAD

**Issue by nicki-krizek** [tomaskrizek/tul-szz-it-nv#15]
[2. - Základy teorie dělitelnosti](https://github.com/tomaskrizek/tul-szz-it-nv/blob/master/02_zaklady_teorie_delitelnosti/02_zaklady_teorie_delitelnosti.md)

| Autor | Reviewer | Stav |
| --- | --- | --- |
| @tomaskrizek |  | :eyes: |
### TODO
- [x] Oveřit postup a výsledek u řešení soustavy kongruencí (Čínská věta o zbytku).
- [x] Rozhodnout, zda uvádět popis / příklad zobecněné čínské věty o zbytku.
- [x] Doplnit priklad na kanonicke rozklady.

**Comment by nicki-krizek** [comment]
Uz k tyhle otazce nejsem schopnej toho dat vic. V uplne posledni casti - Cinska veta o zbytku - prosim o fakt dukladnou kontrolu. Nemel jsem vysledky a uz jsem mlel z posledniho, takze cisla jsem napul strilel od boku.

U zobecnene cinske vety mi nevychazel priklad a ani jsem to moc nechapal, takze jsem tam v podstate nic nedal. Kdyby k tomu nekdo neco mel, tak to muzete doplnit.

**Comment by michalmuzicek** [comment]
V te tabulce Sčítání modulo m mi to nejak nesedi, jestli to je tak ze sloupce se scitaji s radky z modulo 4, tak 3 + 3 = 6 -> 2

**Comment by michalmuzicek** [comment]
A reseni cinske vety je spravne, overil jsem to kalkulackou. 
Co se tyce obecne cinske vety, rozhodne bude lepsi mit nastrel co delat, kdyby ty jednotliva mopula nebyla po 2 nesoudelna, Nevim jestli bych primo uvadel i priklad, protoze opravdu pochybuji ze ti daj spocitat priklad kdyz na cele statnice mas 20 minut, to se spis zeptaj jak bys postupoval.
Takze neco ve smyslu:
najdu nejmensi spolecny nasobek pro dana modula, a ten pak musim rozdelit na nesoudelna nova modula a pak uz pomoci vzorce dostanu serii kongruenci, ktere vyresim, dosadim do vzorce a mam vysledek

**Comment by johnymachine** [comment]
Co se tyce prikladu, jsem pro tam davat uplne simple variantu s vysvetlenymi kroky. Bohate staci napsat v ruce a vyfotit. Lepe se to predstavi podle me...

Co jsem slysel, tak je to jak rika michal, popiste mi slovne jak byste to resil... tak mi prijde dobry mit nejaky mikro priklad pripraven

**Comment by johnymachine** [comment]
Neni tam chybka u společný násobek "tento násobek dělí obě čísla"

**Comment by nicki-krizek** [comment]
To vis, ze je. Ma tam byt: "obe cisla deli tento nasobek". Kdyztak to tam hod, koukam, ze na tom neco upravujes.

**Comment by johnymachine** [comment]
Jak je tam ten euklid 379 = 269 \* 1 + 110

Nemelo by to formalne zacinat 269 = 379 \* 0 + 269?

Uz jsi nepamatuji jestli to je rozdil, nedopocitaval jsem to

**Comment by nicki-krizek** [comment]
Tak, jak to je, by to melo byt spravne. Kdyz se podivas na puvodni kongruenci, tak m = 379, a = 269. Potom se dela euklid pro m,a, tzn. m = a*q + r, coz odpovida.

**Comment by johnymachine** [comment]
Nemá tam být ještě Qi u těch přibližných zlomků, bez toho to není přibližný zlomek. Možná jen chybně označeno?
![image](https://cloud.githubusercontent.com/assets/2737699/15799832/6f176e0c-2a6a-11e6-8527-ba5fa4597fca.png)

**Comment by nicki-krizek** [comment]
Qi si klidne muzes dopocitat, ale nikde ho v retezovem zlomku ani pri vypoctu nevyuzijes, proto jsem ho vynechal.

**Comment by nicki-krizek** [comment]
Oprava, u pribliznych zlomku bys Qi potreboval, ale pokud chces jen spocitat tu kongruenci, nebo kde to je pouzito, staci ti Pi.

**Comment by johnymachine** [comment]
Jj to jsem si myslel

**Comment by nicki-krizek** [comment]
Doplnena zobecnena cinska veta o zbytku, takze by to belo byt komplet. :eyes:

**Comment by johnymachine** [comment]
@tomaskrizek 

Další řešení jsou pouze násobky x0

To je asi špatně přičítáš tam podělené modulo nebo se pletu?

**Comment by nicki-krizek** [comment]
@johnymachine Mas pravdu, pricita se tam to vydeleno modulo. Opraveno.
