### ISSUE TITLE
Tematické okruhy ke SZZ 2015/2016

### ISSUE THREAD

**Issue by johnymachine** [tomaskrizek/tul-szz-it-nv#3]
# Tematické okruhy ke státní závěrečné zkoušce 2015/2016

_Určeno pro studenty NMS oboru Informační technologie FM TUL_

**Postup pro vypracovávání je uveden v příslušné issue #5.**
- [ ] 1. :hourglass:  Základy teorie grafů – souvislost, kostra grafu, eulerovské, hamiltonovské a rovinné grafy. Vybrané grafové algoritmy – prohledávání grafu, minimální kostra, nejkratší cesta. #31
- [ ] 2. :eyes: Základy teorie dělitelnosti – základní pojmy (NSD, NSN, Eukleidův algoritmus), řetězové zlomky, kongruence modulo m, úplná a redukovaná soustava zbytků, počítání v (Zm, +, .), řešení kongruencí 1. stupně a jejich soustav. #15
- [ ] 3. :hourglass: Rekurentní vztahy – základní pojmy, řešení, (ne)homogenní, (ne)lineární rekurentní vztahy, řešení lineárních rekurentních vztahů s konstantními koeficienty a jejich soustav (otázka existence a jednoznačnosti řešení), využití vytvořujících funkcí. #35
- [ ] 4. :eyes: Základy klasické kombinatoriky – princip inkluze a exkluze, Dirichletův princip, zobecněný binomický koeficient, subfaktoriály, Fibonacciho, Catalanova a Stirlingova čísla, problematika rozkladů – varianty, (ne)rozlišitelné objekty, (ne)rozlišitelné skupiny, využití diofantických rovnic a vytvořujících funkcí v oblasti rozkladů. #18 
- [ ] 5. :hourglass:  Vytvořující funkce (obyčejná, exponenciální), otevřený a uzavřený tvar, základní operace s vytvořujícími funkcemi, vytvořující funkce (uzavřený tvar) základních posloupností, věžové polynomy. #36
- [ ] 6. :eyes: Problematika řazení – základní algoritmy a jejich složitost. #10
- [ ] 7. :eyes: Časová náročnost algoritmů. Průměrné a nejhorší chování. Úlohy P, NP a NP-úplné. #37 
- [ ] 8. :eyes: Definice konečného automatu, jazyky rozpoznávané konečnými automaty. #11
- [ ] 9. :eyes: Gramatiky, Chomského hierarchie, vztah gramatik ke konečným strojům. #8
- [ ] 10. :eyes: Turingův stroj, problém zastavení, totální a parciální rozhodnutelnost tříd problémů, rekurzivní a rekurzivně spočetné množiny, jejich vztah. #38 
- [ ] 11. :hourglass: Pojmy šifrování, kódování, symetrické šifry (afinní, Vigener, Hill, jednoduchá transpozice), asymetrické šifry (RSA), Feistelovy šifry, princip, příklady (DES, AES, NDS). #33
- [ ] 12. :hourglass: : Minimální kódy, princip, použití, konstrukce Huffmanova kódu, aritmetické kódy. #29
- [ ] 13. :hourglass: Operační systém a jeho základní úlohy – správa paměti, správa procesů, životní cyklus procesu, přidělování procesoru, správa periferií, problém uváznutí a metody jeho předcházení. #28 
- [ ] 14. :eyes: Databázové systémy – relační a objektový model dat, NoSQL databáze (typy škálování, teorém CAP). #16 
- [ ] 15. :eyes: Normalizace v relačním modelu, bezztrátová dekompozice, datové modelování (ER/ERA diagramy), funkční analýza (DFD diagramy), optimalizace databázových struktur (typy indexů a případy jejich využití). #19 
- [ ] 16. :hourglass: Jazyk SQL (DDL, DML, množinové operace), uložené procedury a spouště v SQL, transakce (ACID, typy konfliktů, stupně izolace). #20
- [ ] 17. :eyes: Programování síťových operací, koncepce socketů a jejich využití, blokující a neblokující komunikační operace. #30 
- [ ] 18. :eyes: WWW aplikace, programování na straně klienta a serveru, jejich možnosti a omezení, nejběžnější používané prostředky a jazyky, uchovávání stavové informace, cookie. #9
- [ ] 19. :hourglass: Alternativní přístupy k programování – funkcionální programování a Lambda kalkulus, náhrada cyklu rekurzí, logické programování, rezoluční mechanismus a jazyk Prolog. #17 
- [ ] 20. :hourglass: Deterministické číslicové signály – popis v časové oblasti, periodicita, DTFT/DFT spektrum, krátkodobá spektrální analýza (STFT) + využití okénkových funkcí, vzorkovací teorém, kvantizace. #21 
- [ ] 21. :hourglass: LTI číslicové systémy – vlastnosti (linearita, kauzalita, stabilita), impulsní odezva (FIR/IIR), frekvenční charakteristika, přenosová funkce, skupinové zpoždění, lineární diferenční rovnice konstantními koeficienty, systém s lineární a minimální fází. #22 
- [ ] 22. :hourglass: Návrh číslicových filtrů – toleranční schéma, základní druhy filtrů (DP, HP, PP, PZ, Allpass), návrh FIR filtrů (metoda oken, metoda vzorkování frekvenční charakteristiky), typy IIR filtrů, porovnání vlastností FIR/IIR filtrů. #27
- [ ] 23. :hourglass: DFT/FFT (radix-2) – vlastnosti a výpočetní složitost, linearní a kruhová konvoluce, rychlý výpočet lineární konvoluce pomocí FFT (metoda overlap-add, overlap-save). #26 
- [ ] 24. :hourglass: Rozdělení a architektury programovatelných zákaznických obvodů, jazyky pro popis technických prostředků, charakteristické rysy jazyka VHDL. #32
- [ ] 25. :hourglass: Zásady návrhu elektronických systémů (základní struktura systému, pravidla synchronního návrhu, přenos signálů mezi časovými doménami). #34
- [ ] 26. :hourglass: Základní architektury počítačů, architektury mikroprocesorů, architektury signálových a grafických procesorů, architektury mikrořadičů, hodnocení výkonnosti počítačů, Amdahlův zákon, výkonnostní rovnice procesoru, srovnání systémů CISC a RISC. #23
- [ ] 27. :hourglass: Paralelní systémy, kategorie, paralelizace zpracování, víceprocesorové systémy, programování v paralelních a distribuovaných systémech – přístupy, prostředky, metody vzájemné synchronizace. #14 
- [ ] 28. :hourglass: Významné průmyslové komunikační systémy a sběrnice v počítačových systémech (CAN, Ethernet, Modbus, SPI, I2C, RS-232, USB, PCI-e, SATA), topologie, charakteristické vlastnosti. #24
- [ ] 29. :eyes: Abstraktní datové typy, seznam, fronta, zásobník, halda, strom, asociativní pole. #12 
- [ ] 30. :hourglass: Vyhledávání lineární a binární, datové struktury optimalizované pro vyhledávání a práce s nimi, binární vyhledávací strom, 2-3 strom, B strom, hashování. #13 

Původní pdf je dostupné zde: [http://www.fm.tul.cz/pro-studenty/dpszz](http://www.fm.tul.cz/pro-studenty/dpszz)

**Comment by johnymachine** [comment]
Dnes večer udělám 27.

**Comment by tomaskrizek** [comment]
Dělám na 6, snad i s malou ukázkou LaTeX formulí.

**Comment by tomaskrizek** [comment]
Pracuju na 18.

**Comment by johnymachine** [comment]
jdu dnes na 29. a 30.

**Comment by tomaskrizek** [comment]
Jdu delat na 9, to mi prijde jako jedna z nejhorsich otazek, tak at to mame za sebou :)

**Comment by johnymachine** [comment]
@to je asi dobre vzit s 8. dohromady (zminit vztah gramatik a konecnych stroju a nekde tam asi popsat silu jednotlivych stroju/automatu)

**Comment by tomaskrizek** [comment]
Dobra, jdu se vrhnout jeste na 8. Uz mi to vkladani matematickych vyrazu jde docela rychle.

**Comment by johnymachine** [comment]
Důležité věci mimo okruh:
- AD a DA převodníky
- zabezpečovací kódy Hamming, CRC
- Protokol TCP/IP
- Mealyho a Moorův automat

_Na zvážení sekce extras_
